### ISSUE TITLE
Unresponsive after empty -joinmessage

### ISSUE THREAD

**Issue by Ridgure** [ZERG3R/PythonBot#7]
***Version*** 
twitchbot-20190103T212814Z-001

***System*** 
Windows 10

***Issue***
Becomes unresponsive after using -joinmessage in chat without a message 

***How to make it repeatable***
Write -joinmessage in chat

***Error_log.log***
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "threading.py", line 862, in run
  File "twitchbot\bot.py", line 277, in saveviewerchat
  File "twitchbot\botcommands.py", line 61, in handle_commands
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "threading.py", line 862, in run
  File "twitchbot\bot.py", line 277, in saveviewerchat
  File "twitchbot\botcommands.py", line 61, in handle_commands
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by ZERG3R** [comment]
doing -joinmessage with no message throws an error, originally tried to stop it by checking the value of join_message but upon doing the same message a second time it isn't caught and still stops the thread, resolved to try-except
